[package]
authors = ["Grafbase"]
description = "Query planning"
edition = "2021"
homepage = "https://grafbase.com"
keywords = ["graphql", "engine", "grafbase"]
license = "MPL-2.0"
name = "engine-query-solver"
repository = "https://github.com/grafbase/grafbase"

[lints]
workspace = true

[dependencies]
grafbase-workspace-hack.workspace = true
id-newtypes = { path = "../id-newtypes", package = "engine-id-newtypes" }
id-derives = { path = "../id-derives", package = "engine-id-derives" }
operation = { path = "../operation", package = "engine-operation" }
walker = { path = "../walker", package = "engine-walker" }
fixedbitset.workspace = true
bitflags.workspace = true
petgraph.workspace = true
itertools.workspace = true
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
strum.workspace = true
hex.workspace = true
schema = { path = "../schema", package = "engine-schema" }
fxhash.workspace = true
hashbrown = "0.15"


[dev-dependencies]
ctor.workspace = true
similar = "2"
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "tracing-log",
    "env-filter",
    "ansi",
] }
insta.workspace = true
tokio.workspace = true
