[package]
name = "graphql-federated-graph"
version = "0.5.0"
edition = "2021"
license = "MPL-2.0"
description = "A serializable federated GraphQL graph representation"
repository = "https://github.com/grafbase/grafbase/tree/main/engine/crates/federated-graph"
keywords = ["graphql", "federation"]

[lints]
workspace = true

[dependencies]
bitflags.workspace = true
wrapping = { path = "../graphql-wrapping-types", package = "graphql-wrapping-types", version = "0.2.0" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
indoc.workspace = true

itertools.workspace = true
cynic-parser = { workspace = true, optional = true }
cynic-parser-deser.workspace = true
indexmap = { optional = true, workspace = true }
grafbase-workspace-hack.workspace = true
extension = { workspace = true, optional = true }


[dev-dependencies]
expect-test = "1.5"
tempfile = "3"
tokio.workspace = true
serde_json.workspace = true
pretty_assertions = "1"

[features]
default = ["render_sdl", "from_sdl", "extension"]
render_sdl = []
from_sdl = ["dep:cynic-parser", "dep:indexmap"]
