[package]
name = "gqlint"
version = "0.1.1"
description = "A GraphQL SDL linting CLI"
keywords = ["graphql", "linter"]
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }
colored.workspace = true
grafbase-workspace-hack.workspace = true
graphql-lint = { path = "../graphql-lint" }
thiserror.workspace = true

[lints]
workspace = true
