[package]
name = "grafbase-hooks-derive"
version = "0.1.0"
description = "A proc macro for the grafbase-hooks crate"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
enumflags2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }

[lints]
workspace = true
