[package]
name = "operation-checks"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
grafbase-workspace-hack.workspace = true
graphql-schema-diff = { path = "../graphql-schema-diff" }

[dev-dependencies]
datatest-stable.workspace = true
expect-test.workspace = true
similar.workspace = true

[lints]
workspace = true

[[test]]
name = "operation_check_tests"
harness = false
