[package]
authors = ["Grafbase"]
description = "The engine schema graph"
edition = "2021"
homepage = "https://grafbase.com"
keywords = ["graphql", "engine", "grafbase"]
license = "MPL-2.0"
name = "engine-schema"
repository = "https://github.com/grafbase/grafbase"
build = "build.rs"

[build-dependencies]
anyhow.workspace = true
rand.workspace = true

[dependencies]
rapidhash = "1"
hex.workspace = true
id-derives = { path = "../id-derives", package = "engine-id-derives" }
id-newtypes = { path = "../id-newtypes", package = "engine-id-newtypes" }
walker = { path = "../walker", package = "engine-walker" }
indexmap.workspace = true
serde.workspace = true
serde_with.workspace = true
strum = { workspace = true, features = ["derive"] }
strum_macros.workspace = true
thiserror.workspace = true
url.workspace = true
gateway-config.workspace = true
fxhash.workspace = true

federated-graph.workspace = true
wrapping.workspace = true
regex.workspace = true
http.workspace = true
serde_regex = "1.1.0"
tracing.workspace = true
grafbase-workspace-hack.workspace = true
extension-catalog.workspace = true

[dev-dependencies]
insta.workspace = true
serde_json.workspace = true
postcard.workspace = true
rstest.workspace = true
pretty_assertions = "1"
tokio.workspace = true
toml.workspace = true
serde_path_to_error = "0.1"
