[package]
name = "hooks"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.86"
grafbase-hooks = "0.1.8"
itertools = "0.14"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:hooks"
