[package]
name = "engine-id-derives"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
grafbase-workspace-hack.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
