name: Build CLI assets
description: Build CLI assets from source

inputs:
  working-directory:
    description: Where to run
    required: false
    default: cli

runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      if: runner.os != 'Windows'
      with:
        bun-version: latest

    - name: Build cli-app
      shell: bash
      working-directory: './packages/cli-app'
      run: |
        npx pnpm i
        npx pnpm run cli-app:build
