[package]
name = "graphql-mocks"
publish = false
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { workspace = true, features = ["dynamic-schema"] }
async-graphql-axum.workspace = true
async-trait.workspace = true
axum = { workspace = true, features = ["tokio", "http1"] }
axum-extra.workspace = true
crossbeam-queue.workspace = true
cynic-parser.workspace = true
futures.workspace = true
futures-util.workspace = true
grafbase-workspace-hack.workspace = true
headers.workspace = true
http.workspace = true
httpsig.workspace = true
httpsig-hyper.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
url.workspace = true

[lints]
workspace = true
