name: Lint
description: Run cargo fmt, clippy, test

runs:
  using: 'composite'
  steps:
    - name: cargo fmt
      shell: bash
      run: |
        cargo fmt --check

    - name: cargo clippy
      shell: bash
      run: |
        cargo clippy \
          --workspace \
          --exclude integration-tests \
          --locked \
          --all-targets \
          --tests -- -D warnings
