name: Lint
description: Run cargo fmt, clippy, test

runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      if: runner.os != 'Windows'
      with:
        bun-version: latest

    - name: cargo fmt
      shell: bash
      run: |
        cargo fmt --check

    - name: cargo clippy
      shell: bash
      run: |
        cargo clippy \
          --workspace \
          --exclude integration-tests \
          --locked \
          --all-targets \
          --tests -- -D warnings
