name: Lint
description: Run cargo fmt, clippy, test

runs:
  using: 'composite'
  steps:
    - uses: uncenter/setup-taplo@v1
      with:
        version: '0.9.3'

    - name: taplo fmt check
      shell: bash
      run: |
        taplo fmt --check
        taplo check

    - name: cargo fmt
      shell: bash
      run: |
        cargo fmt --check

    - name: cargo clippy
      shell: bash
      run: |
        cargo clippy \
          --workspace \
          --exclude integration-tests \
          --locked \
          --all-targets \
          --tests -- -D warnings
