[package]
authors = ["Grafbase"]
description = ""
edition = "2021"
homepage = "https://grafbase.com"
keywords = ["graphql", "engine", "grafbase"]
license = "MPL-2.0"
name = "engine-operation"
repository = "https://github.com/grafbase/grafbase"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []
qp = []

[dependencies]
blake3.workspace = true
cynic-parser.workspace = true
strum.workspace = true
grafbase-telemetry.workspace = true
id-newtypes = { path = "../id-newtypes", package = "engine-id-newtypes" }
id-derives = { path = "../id-derives", package = "engine-id-derives" }
config = { package = "engine-config", path = "../config" }
itertools.workspace = true
lasso2 = { version = "0.8.2", features = ["serialize"] }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
tracing.workspace = true

operation-normalizer = { path = "../../operation-normalizer" }
schema = { path = "../schema", package = "engine-schema" }
walker = { path = "../walker", package = "engine-walker" }
grafbase-workspace-hack.workspace = true
serde_with = { workspace = true, features = ["hex"] }

