[package]
name = "subgraph_request"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
grafbase-hooks.workspace = true
serde_json.workspace = true

[lib]
crate-type = ["cdylib"]
