[package]
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license = "MPL-2.0"
name = "extension"
repository.workspace = true

[lints]
workspace = true


[dependencies]
semver = { workspace = true, features = ["serde"] }
grafbase-workspace-hack.workspace = true
serde.workspace = true
url.workspace = true
reqwest.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile = "3"
